//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("ChilliSource Mobile")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0-alpha.560+Branch.develop.Sha.8c5b2be04b221e0c19b52a8be01d52d7c3401ad3")]
[assembly: AssemblyCopyright("Copyright (c) BlueChilli Technology PTY LTD")]

